In [1]:
import torch
import numpy as np

In [2]:
# pytorch datatypes - tensors

In [3]:
torch.tensor(10)

tensor(10)

In [4]:
torch.tensor([10,20])

tensor([10, 20])

In [5]:
scalar = torch.tensor(10)

In [6]:
type(scalar)

torch.Tensor

In [7]:
vector = torch.tensor([10,20])

In [8]:
type(vector)

torch.Tensor

In [9]:
scalar + 5

tensor(15)

In [10]:
scalar - 10

tensor(0)

In [11]:
scalar * 3

tensor(30)

In [12]:
scalar.dim() #boyut

0

In [13]:
scalar.shape 

torch.Size([])

In [14]:
scalar.item()

10

In [15]:
type(scalar.item())

int

In [16]:
numpy_int = np.int32(10)

In [17]:
numpy_int - 10

np.int32(0)

In [18]:
numpy_int / 2

np.float64(5.0)

In [19]:
scalar_from_np = torch.tensor(numpy_int)

In [20]:
scalar_from_np

tensor(10, dtype=torch.int32)

In [21]:
scalar_from_np.dtype

torch.int32

In [22]:
scalar.dtype

torch.int64

In [23]:
new_scalar = torch.tensor(25, dtype=torch.int32)

In [24]:
new_scalar.dtype

torch.int32

In [25]:
tensor_float = torch.tensor(3.14)

In [26]:
tensor_float

tensor(3.1400)

In [27]:
tensor_float.dtype

torch.float32

In [28]:
tensor_float_64 = torch.tensor(3.14, dtype=torch.float64)

In [29]:
tensor_float_64

tensor(3.1400, dtype=torch.float64)

In [30]:
tensor_float_64 * 2

tensor(6.2800, dtype=torch.float64)

In [31]:
# vectors

In [32]:
vector = torch.tensor([2, 3])

In [33]:
vector

tensor([2, 3])

In [34]:
vector.ndim

1

In [35]:
vector.shape

torch.Size([2])

In [36]:
vector = torch.tensor([1,2,3])

In [37]:
vector.ndim

1

In [38]:
vector.shape

torch.Size([3])

In [39]:
# count # of [ in order to figure out number of dimensions
# count elements in order to figure out shape

In [40]:
matrix = torch.tensor([[1,2],[3,4]])

In [41]:
matrix.ndim

2

In [42]:
matrix.shape

torch.Size([2, 2])

In [43]:
tensor_example = torch.tensor([[[1,2,3],[3,4,5],[4,5,6]]])

In [44]:
tensor_example

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 5, 6]]])

In [45]:
tensor_example.ndim

3

In [46]:
tensor_example.shape

torch.Size([1, 3, 3])

In [47]:
# this means 1 dimension of 3 by 3

In [48]:
# deep dive into dtypes - https://docs.pytorch.org/docs/stable/tensors.html#data-types

In [49]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # default or custom?
                               device=None, # cpu, gpu?
                               requires_grad=False) # If autograd should record operations on the returned tensor

In [50]:
float_32_tensor.shape

torch.Size([3])

In [51]:
float_32_tensor.dtype

torch.float32

In [52]:
float_32_tensor.device

device(type='cpu')

In [53]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)

In [54]:
float_16_tensor.dtype

torch.float16