In [1]:
import torch
import numpy as np

In [2]:
# remember we can create random ints, arrays etc. in numpy

In [3]:
random_array = np.random.randn(3,5)

In [4]:
random_array

array([[ 1.62959537e+00,  6.19879903e-01,  1.97746138e+00,
        -1.97683559e-01,  2.44242485e-01],
       [-2.21822441e+00,  2.06197628e-01, -3.08066800e-02,
         6.51083796e-01, -6.58883498e-02],
       [-2.71421087e-05, -3.65934322e-01, -2.37994427e+00,
         1.77635984e+00,  2.39952691e-01]])

In [5]:
type(random_array)

numpy.ndarray

In [6]:
random_array.shape

(3, 5)

In [7]:
random_array.ndim

2

In [8]:
# let's do this in pytorch

In [9]:
random_matrix = torch.rand(size=(3, 5))

In [10]:
random_matrix

tensor([[0.6148, 0.9835, 0.7634, 0.3738, 0.9267],
        [0.3719, 0.6065, 0.0261, 0.9292, 0.4421],
        [0.1291, 0.8916, 0.6649, 0.0658, 0.2529]])

In [11]:
random_matrix.ndim

2

In [12]:
random_matrix.shape

torch.Size([3, 5])

In [13]:
random_matrix.dtype

torch.float32

In [14]:
# we generally use 32 * 32 or 224 * 224 images in vision dl problems

In [15]:
random_image_matrix = torch.rand(size=(224, 224, 3))

In [16]:
random_image_matrix

tensor([[[0.0936, 0.2299, 0.2626],
         [0.2803, 0.9564, 0.9312],
         [0.5141, 0.4227, 0.1050],
         ...,
         [0.7348, 0.6126, 0.1472],
         [0.4272, 0.7645, 0.4778],
         [0.2616, 0.7274, 0.7939]],

        [[0.2680, 0.3332, 0.5018],
         [0.6768, 0.6129, 0.1895],
         [0.9412, 0.9173, 0.4465],
         ...,
         [0.1685, 0.1519, 0.2510],
         [0.3943, 0.8021, 0.8451],
         [0.4669, 0.0154, 0.6080]],

        [[0.1925, 0.5307, 0.8380],
         [0.3280, 0.3602, 0.1170],
         [0.8152, 0.2906, 0.2999],
         ...,
         [0.0365, 0.8607, 0.8734],
         [0.2508, 0.3828, 0.4812],
         [0.9223, 0.1994, 0.9603]],

        ...,

        [[0.1889, 0.2691, 0.8022],
         [0.2931, 0.1488, 0.8613],
         [0.9405, 0.7114, 0.5152],
         ...,
         [0.0181, 0.8176, 0.9698],
         [0.2786, 0.9823, 0.7732],
         [0.3256, 0.3372, 0.7755]],

        [[0.7879, 0.6806, 0.2421],
         [0.6386, 0.5686, 0.1879],
         [0.

In [17]:
random_image_matrix.ndim

3

In [18]:
random_image_matrix.shape

torch.Size([224, 224, 3])

In [19]:
# we can create zeros and ones if we need some for matrix multiplication or anything else

In [20]:
zeros = torch.zeros(size=(3, 2))

In [21]:
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
ones = torch.ones(size=(3, 4))

In [23]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
# or we can create ranges

In [25]:
vector_with_arange = torch.arange(start=0, end=10, step=1)

In [26]:
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
vector_with_arange = torch.arange(start=0, end=10, step=2)

In [28]:
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [29]:
# let's say i need a similar vector with ones

In [30]:
similar_ones = torch.ones_like(input=vector_with_arange)

In [31]:
similar_ones

tensor([1, 1, 1, 1, 1])

In [32]:
# basic math operations

In [33]:
tensor = torch.tensor([1, 2, 3])

In [34]:
tensor + 15

tensor([16, 17, 18])

In [35]:
tensor * 12

tensor([12, 24, 36])

In [36]:
tensor * 3.14

tensor([3.1400, 6.2800, 9.4200])

In [37]:
tensor

tensor([1, 2, 3])

In [38]:
tensor = tensor + 10

In [39]:
tensor

tensor([11, 12, 13])

In [40]:
# we also have native methods for that

In [41]:
tensor.subtract(10)

tensor([1, 2, 3])

In [42]:
tensor

tensor([11, 12, 13])

In [43]:
tensor = tensor.subtract(10)

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
tensor.multiply(20)

tensor([20, 40, 60])

In [46]:
tensor.add(20)

tensor([21, 22, 23])

In [47]:
tensor.divide(2)

tensor([0.5000, 1.0000, 1.5000])

In [48]:
# can we only operate with scalars?

In [49]:
tensor * tensor

tensor([1, 4, 9])

In [50]:
tensor + tensor

tensor([2, 4, 6])

In [51]:
tensor - tensor

tensor([0, 0, 0])

In [52]:
tensor / tensor

tensor([1., 1., 1.])

In [53]:
# beware, in this case shapes should make sense

In [54]:
tensor2 = torch.tensor([4,5])

In [55]:
tensor + tensor2

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [56]:
tensor * tensor2

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0