In [1]:
import torch

In [2]:
tensor = torch.arange(0, 50, 5)

In [3]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
tensor.min()

tensor(0)

In [5]:
tensor.max()

tensor(45)

In [6]:
tensor.sum()

tensor(225)

In [7]:
tensor.median()

tensor(20)

In [8]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [9]:
# as you can see sometimes we get data type errors. we should know how to change dtypes when necessary

In [10]:
tensor.dtype

torch.int64

In [11]:
tensor.type(torch.float)

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [12]:
tensor = tensor.type(torch.float)

In [13]:
tensor.mean()

tensor(22.5000)

In [14]:
# positional max, min (arg max min)

In [15]:
tensor

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [16]:
tensor.max()

tensor(45.)

In [17]:
tensor.argmax()

tensor(9)

In [18]:
#9th index

In [19]:
tensor[9]

tensor(45.)

In [20]:
tensor[0]

tensor(0.)

In [21]:
#tensor[0][0] -> will throw error

In [22]:
# index works as long as dimension fits

In [23]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [24]:
matrix[0]

tensor([1, 2, 3])

In [25]:
matrix[0][0]

tensor(1)

In [26]:
#matrix[0][0][0]

In [27]:
# manipulating tensors: reshaping, stacking, squeezing, unsqueezing

In [28]:
x = torch.arange(1,10,1)

In [29]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
x.shape

torch.Size([9])

In [31]:
x_reshaped = x.reshape(1,9)

In [32]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [33]:
x_reshaped.shape

torch.Size([1, 9])

In [34]:
# numbers should make sense

In [35]:
# x_reshaped = x.reshape(1,20) -> will throw an error

In [36]:
x_reshaped = x.reshape(3,3)

In [37]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [38]:
x_reshaped = x.reshape(9,1)

In [39]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [40]:
# view function also behaves like reshape

In [41]:
x_view = x.view(9,1)

In [42]:
x_view

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [43]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
# there are similarities & differences btw reshape & view. let's see

In [45]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [46]:
x_reshaped[0] = 20

In [47]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [48]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [49]:
x_view[0] = 10

In [50]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [51]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [52]:
# they both change the original tensor if there is a change in them

In [53]:
# however view only works with contigious tensors

In [54]:
#https://medium.com/analytics-vidhya/pytorch-contiguous-vs-non-contiguous-tensor-view-understanding-view-reshape-73e10cdfa0dd

In [55]:
# so that's why this will happen

In [56]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

In [57]:
x.is_contiguous()

True

In [58]:
y = x.t()  # transpose -> NOT contiguous

In [59]:
y.is_contiguous()

False

In [60]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [61]:
y.view(1,6)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [62]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [63]:
# as you can see the order is not what it used to be since we transposed this tensor

In [64]:
# Stacking

In [65]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [66]:
torch.stack([x,x,x,x], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [67]:
torch.stack([x,x,x,x], dim=1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [68]:
# squeeze & unsqueeze -> removing all single dimensions from a tensor

In [69]:
x.shape

torch.Size([2, 3])

In [70]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [71]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [72]:
y = x.unsqueeze(dim=0)

In [73]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [74]:
y.shape

torch.Size([1, 2, 3])

In [75]:
z = y.unsqueeze(dim=0)

In [76]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [77]:
z.shape

torch.Size([1, 1, 2, 3])

In [78]:
t = z.squeeze()

In [79]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [80]:
t.shape

torch.Size([2, 3])

In [81]:
y.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [82]:
y.squeeze().shape

torch.Size([2, 3])

In [83]:
# permute -> rearrange the order of axes values

In [84]:
x = torch.rand(size=(224, 224, 3))

In [85]:
x.shape

torch.Size([224, 224, 3])

In [86]:
x_permuted = x.permute(2, 0, 1) # axis 0->1, 1->2, 2->0

In [87]:
x_permuted.shape

torch.Size([3, 224, 224])

In [88]:
# indexing & slicing

In [89]:
a = torch.arange(1,10,1)

In [90]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
a = a.reshape(1,3,3)

In [92]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [93]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [94]:
a[0][0]

tensor([1, 2, 3])

In [95]:
a[0][0][0]

tensor(1)

In [96]:
# Get all values of 0th dimension and the 0 index of 1st dimension
a[:, 0]

tensor([[1, 2, 3]])

In [97]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
a[:, :, 1]

tensor([[2, 5, 8]])

In [98]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
a[:, 1, 1]

tensor([5])

In [99]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
a[0, 0, :] # same as a[0][0]

tensor([1, 2, 3])

In [100]:
# random seeds

In [101]:
RANDOM_SEED=10
#torch.manual_seed(seed=RANDOM_SEED) 
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1064, 0.8068, 0.4196, 0.7809],
        [0.7045, 0.8540, 0.3854, 0.2571],
        [0.6447, 0.0206, 0.9248, 0.0264]])