In [1]:
import torch

In [2]:
torch.cuda.is_available() # check if gpu is available in your machine

False

In [3]:
torch.backends.mps.is_available() # check if gpu is available in your machine (Mac silicons)

False

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu" # other than mac

In [5]:
device

'cpu'

In [6]:
device = "mps" if torch.backends.mps.is_available() else "cpu" # mac

In [7]:
device

'cpu'

In [8]:
# or just use this code for all

In [9]:
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU 
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU 
else:
    device = "cpu" # Default to CPU if no GPU is available

In [10]:
device

'cpu'

In [11]:
# what about the rest of the code?

In [12]:
tensor = torch.tensor([1, 2, 3])

In [13]:
tensor

tensor([1, 2, 3])

In [14]:
tensor.device

device(type='cpu')

In [15]:
# i have a gpu available but the tensors that i created defaults to cpu
# what can i do?

In [16]:
# 1) Manually handle everything

In [17]:
tensor_on_gpu = tensor.to(device)

In [18]:
tensor_on_gpu.device

device(type='cpu')

In [19]:
# this is great but it can create some hassle for you when you want to move back and forth
# why would you want to move back to cpu btw?

In [20]:
tensor_on_gpu.numpy()

array([1, 2, 3])

In [21]:
# this will give you an error if you are on gpu since numpy does not leverage gpu

In [22]:
tensor_numpy = tensor_on_gpu.cpu().numpy()

In [23]:
tensor_numpy

array([1, 2, 3])

In [24]:
#2) second option would be to use the context manager that came after 2.x versions

In [25]:
device

'cpu'

In [26]:
with torch.device(device):
    # All tensors created in this block will be on device
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20, 30) # we haven't covered layers yet but this will be created on gpu as well

In [27]:
tensor2.device

device(type='cpu')

In [28]:
layer.weight.device

device(type='cpu')

In [29]:
#3) third option would be to use global definition of device for pytorch that came after 2.x versions

In [30]:
device

'cpu'

In [31]:
torch.set_default_device(device)

In [32]:
tensor3 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(20, 30)

In [33]:
tensor3.device

device(type='cpu')

In [34]:
layer2.weight.device

device(type='cpu')

In [35]:
torch.set_default_device("cpu")

In [36]:
tensor3.device

device(type='cpu')

In [37]:
tensor3 = torch.tensor([1,2,3])

In [38]:
tensor3.device

device(type='cpu')

In [39]:
# we can change the device back and forth globally like this but we need be careful again as we see in this example